title: YerIn
description: "Satellite - Jekyll blog"
url: "https://yerinny0518.github.io"
baseurl: "/yerinny.github.io"   # ★ 프로젝트 사이트는 꼭 필요

remote_theme: byanko55/jekyll-theme-satellite
plugins:
  - jekyll-remote-theme

locale: ko_KR
timezone: Asia/Seoul
